version: '3.8'

services:
    vault:
      container_name: vault
      image: vault:1.11.3
      ports:
        - "8200:8200"
      environment:
        - "VAULT_DEV_ROOT_TOKEN_ID=00000000-0000-0000-0000-000000000000"
        - "VAULT_TOKEN=00000000-0000-0000-0000-000000000000"
        - "VAULT_ADDR=http://127.0.0.1:8200"
      volumes:
        - ./vault-init.sh:/usr/local/bin/vault-init.sh
